spring:
  application:
    name: ms-rutaexpress-catalog
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:8080}